### ISSUE TITLE
Excuse me, may I ask how to split the interactions for K latent intents? Just randomly split them?

### ISSUE THREAD

**Issue by hhhiddleston** [xiangwang1223/disentangled_graph_collaborative_filtering#2]

**Comment by xiangwang1223** [comment]
Thanks for your interest. No interactions are split for the latent intents. Assuming there are K latent intents behind every single interaction, DGCF will use the dynamic neighbor routing mechanism and embedding propagation mechanism to automatically refine the distribution of each interaction over K intents.

Hope it is helpful.

**Comment by hhhiddleston** [comment]
> Thanks for your interest. No interactions are split for the latent intents. Assuming there are K latent intents behind every single interaction, DGCF will use the dynamic neighbor routing mechanism and embedding propagation mechanism to automatically refine the distribution of each interaction over K intents.
> 
> Hope it is helpful.

Thanks for the instant reply. I was a little confused about the fig.2 in the paper. Now I have understood! Thx!
